### ISSUE TITLE
Piazza Link

### ISSUE THREAD

**Issue by saulsb** [howardisaacson/Intro-to-Astro-2020#1]
The link to join your class (second bullet under Announcement about Piazza) leads me to a 404 Error.

**Comment by murphyjm** [comment]
Hmm, where are you seeing the link that you're using? You should've received an email from Piazza just now to enroll you in the class. I can update the link that you were trying to use, I'm just having trouble finding the one you were using.

**Comment by saulsb** [comment]
I didn't receive an email from Piazza; I don't have an account yet so maybe that's why? Also, the link I tried was in the folder titled Week1_Intro_unix_python.

**Comment by murphyjm** [comment]
Ah, in any case the link in the Week 1 readme should be fixed now. Thanks for pointing that out!
